import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline{
  agent any
  environment{
    appName = "variable" 
  }
  stages{
    stage("Fase 1"){
      steps{
        script{			
          sh "echo 'hola mundo'"
        }
      }
    }
    stage("Fase 2"){
      steps{
        script{
          sh "echo 'Terminado Fase 1'"
        }
      }
    }
  }
  post{
      always{          
          deleteDir()
           sh "echo 'fase always'"
      }
      success{
          sh "echo 'fase success'"
      }

      failure{
            sh "echo 'fase failure'"
      } 
  }
}

